name: Build, Push & Execute Images
on:
  pull_request:
  push:
    branches:
      - main

env:
  BUILD_REPO_NAME: core
  REGISTRY_NAME: public.ecr.aws/resim
  RESIM_PASSWORD: ${{ secrets.RESIM_PASSWORD }}
  RESIM_USERNAME: ${{ secrets.RESIM_USERNAME }}
  PROJECT_NAME: "mgrijalva metrics 2 testing"
  SIM_SYSTEM: SYSTEM
  AUTH_URL: https://resim-dev.us.auth0.com
  API_URL: https://api.resim.io/v1/

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-push-hello-world:
    name: Create & Push New Hello World Build Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_image_tag.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_RW_ROLE }}
          aws-region: us-east-1

      - name: Log in to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_NAME }}

      - name: Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_NAME }}/${{ env.BUILD_REPO_NAME }}
          tags: |
            type=ref,event=branch,prefix=sandbox-hello-world-
            type=ref,event=pr,prefix=sandbox-hello-world-pr-
            type=sha,prefix=sandbox-hello-world-

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            hello_world:
              - systems/hello_world/**

      - name: Set up Docker Buildx
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.hello_world == 'true'}}
        uses: docker/setup-buildx-action@v3

      - name: Docker Build Push
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.hello_world == 'true'}}
        id: build-push-build
        uses: docker/build-push-action@v5
        with:
          context: ./systems/hello_world
          file: ./systems/hello_world/Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      - uses: imjasonh/setup-crane@v0.4

      - name: Retag existing image
        if: ${{ github.event_name == 'pull_request' && steps.filter.outputs.hello_world == 'false'}}
        id: retag_image
        run: |
          export IMAGE_URL=$(echo "${{ steps.docker_meta.outputs.tags }}" | tail -n 1)
          export IMAGE_TAG="${IMAGE_URL##*:}"
          crane tag ${{ env.REGISTRY_NAME }}/${{ env.BUILD_REPO_NAME }}:sandbox-hello-world-${{ github.event.pull_request.base.ref }} $IMAGE_TAG

      - name: Get Image Tag
        id: get_image_tag
        run: |
          export IMAGE_URL=$(echo "${{ steps.docker_meta.outputs.tags }}" | tail -n 1)
          echo "image_tag=$IMAGE_URL" >> $GITHUB_OUTPUT

  create-hello-world-build:
    name: Create a build for the hello-world image
    runs-on: ubuntu-latest
    needs: [build-push-hello-world]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch ReSim CLI
        run: |
          curl -L https://github.com/resim-ai/api-client/releases/latest/download/resim-linux-amd64 -o resim-cli
          chmod +x resim-cli

      - name: Determine Branch Name and Commit SHA
        id: determine_branch_and_sha
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BRANCH_NAME=${{ env.HEAD_REF }}" >> $GITHUB_ENV
            echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ env.REF_NAME }}" >> $GITHUB_ENV
            echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          fi
        env:
          HEAD_REF: ${{ github.head_ref }}
          REF_NAME: ${{ github.ref_name }}

      - name: Select Project
        run: |
          ./resim-cli --auth-url ${AUTH_URL} --url ${API_URL} projects list
          ./resim-cli --auth-url ${AUTH_URL} --url ${API_URL} projects select "${PROJECT_NAME}"

      - name: Register Hello World Build in ReSim
        run: |
          export RESIM_HELLO_WORLD_IMAGE_TAG=${{ needs.build-push-hello-world.outputs.image_tag }}
          ./resim-cli --auth-url ${AUTH_URL} --url ${API_URL} builds create --image $RESIM_HELLO_WORLD_IMAGE_TAG \
            --system $SIM_SYSTEM --name "Hello World Build" --description "A simple hello-world example" \
            --version "${{ env.COMMIT_SHA }}" --branch "${{ env.BRANCH_NAME }}" --auto-create-branch --github >> $GITHUB_ENV
      - name: Run metrics 2.0 batch
        run: |
          ./resim-cli --auth-url ${AUTH_URL} --url ${API_URL} batch create --build-id ${build_id} --experiences "asdfadsf" --pool-labels "resim:metrics2:k8s" --metrics-set "hello metrics"
